# Generated by Django 5.2.14 on 2026-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=80)),
                ("highlight", models.CharField(max_length=80)),
                ("highlight_label", models.CharField(max_length=120)),
                ("detail", models.CharField(max_length=220)),
                ("color", models.CharField(max_length=40)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("project_type", models.CharField(blank=True, max_length=120)),
                ("budget", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=180)),
                ("role", models.CharField(max_length=180)),
                ("type", models.CharField(max_length=80)),
                ("location", models.CharField(max_length=120)),
                ("start_date", models.CharField(max_length=80)),
                ("end_date", models.CharField(blank=True, max_length=80, null=True)),
                ("current", models.BooleanField(default=False)),
                ("highlights", models.JSONField(default=list)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("special", models.BooleanField(default=False)),
                ("special_label", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "experience entries",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("primary_role", models.CharField(max_length=160)),
                ("headline", models.CharField(max_length=220)),
                ("summary", models.TextField()),
                ("location", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("availability", models.CharField(max_length=180)),
                ("cv_url", models.CharField(blank=True, max_length=255)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("social_links", models.JSONField(blank=True, default=list)),
                ("about_sections", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=180)),
                ("subtitle", models.CharField(max_length=255)),
                ("short_description", models.TextField()),
                ("full_description", models.TextField()),
                ("categories", models.JSONField(default=list)),
                ("featured", models.BooleanField(default=False)),
                ("biggest_project", models.BooleanField(default=False)),
                ("confidential", models.BooleanField(default=False)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("year", models.CharField(blank=True, max_length=40)),
                ("start_date", models.CharField(blank=True, max_length=40)),
                ("end_date", models.CharField(blank=True, max_length=40, null=True)),
                ("status", models.CharField(max_length=80)),
                ("role", models.CharField(max_length=180)),
                ("project_type", models.CharField(max_length=180)),
                (
                    "cover_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("features", models.JSONField(blank=True, default=list)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("challenges", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=120)),
                ("icon", models.CharField(max_length=80)),
                ("skills", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
