# Generated by Django 5.2.14 on 2026-08-09 20:25

import apps.portfolio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                upload_to=apps.portfolio.models.project_cover_path,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="draft",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from the public API while checked. Use for incomplete entries.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Resized to at most 1600×900 and re-encoded to WebP on save.",
                max_length=255,
                null=True,
                upload_to=apps.portfolio.models.project_cover_path,
            ),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Resized to at most 1920×1080 and re-encoded to WebP on save.",
                        max_length=255,
                        upload_to=apps.portfolio.models.project_gallery_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        upload_to=apps.portfolio.models.project_gallery_path,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("image_type", models.CharField(blank=True, max_length=40)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
