# Generated by Django 5.2.14 on 2026-08-10 06:23

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_cover_thumbnail_project_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                help_text="Shown in the site navigation. Resized to at most 256×256 and re-encoded to PNG (crisp edges, transparency preserved) on save.",
                max_length=255,
                null=True,
                upload_to=apps.portfolio.models.site_logo_path,
            ),
        ),
    ]
