# Generated by Django 5.2.14 on 2026-08-10 10:43

import apps.portfolio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_profile_site_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="cv_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text='The PDF served by every "Download CV" button on the site.',
                max_length=255,
                null=True,
                upload_to=apps.portfolio.models.cv_file_path,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
